=== Tiger66639/code-0/FrameNetSin/Data/docs/semtypesV1_1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This is the DTD for the semtypes.xml file, which contains information
about the semantic types. Its format can be summarized as:

<semTypes>
  <semType>*
    <definition>
    <superTypes>
       <superType>*

-->
<!ELEMENT semTypes (semType*)>

<!ATTLIST semTypes 
          XMLCreated  CDATA     #REQUIRED>

<!ELEMENT semType (definition, superTypes)>

<!ATTLIST semType 
          ID       NMTOKEN         #REQUIRED
          name      CDATA         #REQUIRED
          abbrev       CDATA    #REQUIRED
          cDate     CDATA         #IMPLIED> 

<!ELEMENT definition (#PCDATA)>

<!ELEMENT superTypes (superType*)>

<!ELEMENT superType EMPTY>

<!ATTLIST superType
          superTypeName CDATA    #REQUIRED
          supId NMTOKEN #REQUIRED>

<!ELEMENT annotation (annotated, total)>

<!ELEMENT annotated (#PCDATA)>

<!ELEMENT total (#PCDATA)>

=== Tiger66639/code-0/FrameNetSin/Data/semtypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE semTypes SYSTEM "docs/semtypesV1_1.dtd">

<semTypes XMLCreated="Wed Jul 26 14:59:54 PDT 2006">
  <semType ID="2" name="Body_of_water" abbrev="Body-of-water">
    <definition>Labels LU's which designate bodies of water.  The limits of a body of water are defined in terms of the land that borders the water.  Equivlent to WN Body of water.
(Appropriate for LU's in Locale frame and its descendants.)</definition>
    <superTypes>
      <superTypes superTypeName="Region" supId="17" />
    </superTypes>
  </semType>
  <semType ID="3" name="Running-water" abbrev="Running-water">
    <definition>Labels LU's that designate geographical features of running water.  Equivalent to WN watercourse.
(Appropriate for LU's in Locale and descendants of Locale.)</definition>
    <superTypes>
      <superTypes superTypeName="Body_of_water" supId="2" />
    </superTypes>
  </semType>
  <semType ID="5" name="Sentient" abbrev="Sentient">
    <definition>Marks FEs whose fillers are sentient beings; dogs, definitely; bacteria, probably not; comatose people, planeria, maybe.  This is a common-sense type, with fuzzy boundaries, not a precise bio-medical category.</definition>
    <superTypes>
      <superTypes superTypeName="Animate_being" supId="65" />
    </superTypes>
  </semType>
  <semType ID="7" name="Landform" abbrev="Landform">
    <definition>Labels LU's which designate land geography/topography.  Such LU's give some information about the 3-D shape of the land.
(Appropriate for LU's in Locale frame and its descendants.)</definition>
    <superTypes>
      <superTypes superTypeName="Region" supId="17" />
    </superTypes>
  </semType>
  <semType ID="8" name="Activity" abbrev="Activity">
    <definition>Labels Activity Aktionsart.  Used for events that fundamentally denote the 'Ongoing' subpart of an X-schema.  E.g. We walked _for an hour_.  Note that most verbs which inherently denote an Activity can be used as Accomplishments when a distinct goal is mentioned:  We walked to the</definition>
    <superTypes>
      <superTypes superTypeName="Event" supId="75" />
    </superTypes>
  </semType>
  <semType ID="9" name="Transparent Noun" abbrev="Transparent Noun">
    <definition>Transparent noun.</definition>
    <superTypes>
      <superTypes superTypeName="Lexical_type" supId="180" />
    </superTypes>
  </semType>
  <semType ID="10" name="Body_part" abbrev="BodyPt">
    <definition>Type for all body parts of humans and animals.</definition>
    <superTypes>
      <superTypes superTypeName="Physical_object" supId="68" />
    </superTypes>
  </semType>
  <semType ID="13" name="Positive_judgement" abbrev="Positive_judgement">
    <definition>This semantic type is used to mark words in the Judgement frame and related frames (like Punishments_and_rewards) as involving a positive judgement by a Cognizer, i.e. a Cognizer respecting or approving to actions of an Evaluee.  (See Negative_judgement.)</definition>
    <superTypes>
      <superTypes superTypeName="Affect_describing" supId="213" />
    </superTypes>
  </semType>
  <semType ID="14" name="Negative_judgement" abbrev="Negative_judgement">
    <definition>This type is used to mark lexical units involving a negative judgement (on the part of the Judge) in frames related to Judgement, such as Punishment.  It is also used to denote the opinion of the speaker associated with words in several other frames (such as Frugality and Appearance), including a more heterogeneous variety of words having the prefixes 'mis-', 'under-', and 'over-'.  It is also used of words which indicate undesirable effects, e.g. warp, in frames such as Reshaping.</definition>
    <superTypes>
      <superTypes superTypeName="Affect_describing" supId="213" />
    </superTypes>
  </semType>
  <semType ID="15" name="Container" abbrev="Container">
    <definition>Marks FEs extending over constituents whose denotatum is a container.</definition>
    <superTypes>
      <superTypes superTypeName="Physical_object" supId="68" />
    </superTypes>
  </semType>
  <semType ID="16" name="Non-Lexical Frame" abbrev="Non-Lexical Frame">
    <definition>Used to describe frames that don't have corresponding lexical items in English.</definition>
    <superTypes>
      <superTypes superTypeName="Framal_type" supId="179" />
    </superTypes>
  </semType>
  <semType ID="17" name="Region" abbrev="Land">
    <definition>Labels LU's that designate solid ground defined in terms of the shape of a border with water.  Equivalent to WN Geological formation, which, however, is not a supertype of Body of Water.</definition>
    <superTypes>
      <superTypes superTypeName="Location" supId="54" />
    </superTypes>
  </semType>
  <semType ID="19" name="Achievement" abbrev="Achievement">
    <definition>Aspectual type for predicators which describe "achievements"; e.g. Gloria recognized the boy (in an instant) *for an hour. (One kind of "telic", the other is "accomplishment")</definition>
    <superTypes>
      <superTypes superTypeName="Event" supId="75" />
    </superTypes>
  </semType>
  <semType ID="20" name="Accomplishment" abbrev="Accomplishment">
    <definition>Aspectual type for predicators that describe "accomplishments", which include both activities and their culmination e.g. They climbed the mountain (in two days). N.B. _They climbed the mountain for two days_ describes an activity, not an accomplishment-- there is no implication that they reached the top.</definition>
    <superTypes>
      <superTypes superTypeName="Event" supId="75" />
    </superTypes>
  </semType>
  <semType ID="52" name="Non-perspectivalized_frame" abbrev="Non-p">
    <definition>This semantic type marks frames that do not impose a perspective on the situation portrayed by the frame.  An example is the Commerce frame, in which a Lexical Unit like commerce.n denotes an interaction between participants (Buyer, Seller, Money, and Goods) but profiles none of them.  An important consequence of the lack of perspective is that the opposition of core, periperal, and extrathematic frame elements is not relevant.</definition>
    <superTypes>
      <superTypes superTypeName="Framal_type" supId="179" />
    </superTypes>
  </semType>
  <semType ID="54" name="Location" abbrev="LOCN">
    <definition>WN synset: location</definition>
    <superTypes>
      <superTypes superTypeName="Physical_object" supId="68" />
    </superTypes>
  </semType>
  <semType ID="55" name="Content" abbrev="CONT">
    <definition>WN synset: content, cognitive content, mental object</definition>
    <superTypes>
      <superTypes superTypeName="State_of_affairs" supId="177" />
    </superTypes>
  </semType>
  <semType ID="56" name="Message" abbrev="MESG">
    <definition>WN synset: message, content, subject matter, substance</definition>
    <superTypes>
      <superTypes superTypeName="State_of_affairs" supId="177" />
    </superTypes>
  </semType>
  <semType ID="57" name="Social relation" abbrev="SOCR">
    <definition>WN synset: social relation</definition>
    <superTypes>
      <superTypes superTypeName="Relation" supId="174" />
    </superTypes>
  </semType>
  <semType ID="58" name="Organization" abbrev="ORGZ">
    <definition>WN synset: organization, organisation</definition>
    <superTypes>
      <superTypes superTypeName="Group" supId="76" />
    </superTypes>
  </semType>
  <semType ID="59" name="Quantity" abbrev="QUAN">
    <definition>WN synset: measure, quantity, amount, quantum</definition>
    <superTypes>
      <superTypes superTypeName="Attribute" supId="154" />
    </superTypes>
  </semType>
  <semType ID="60" name="Shape" abbrev="SHAP">
    <definition>WN synset: shape, form</definition>
    <superTypes>
      <superTypes superTypeName="Attribute" supId="154" />
    </superTypes>
  </semType>
  <semType ID="61" name="Artifact" abbrev="ARTF">
    <definition>WN synset: artifact, artefact</definition>
    <superTypes>
      <superTypes superTypeName="Physical_object" supId="68" />
    </superTypes>
  </semType>
  <semType ID="62" name="Structure" abbrev="STRC">
    <definition>WN synset: structure, construction</definition>
    <superTypes>
      <superTypes superTypeName="Artifact" supId="61" />
    </superTypes>
  </semType>
  <semType ID="63" name="Material" abbrev="STUF">
    <definition>WN synset: material, stuff</definition>
    <superTypes>
      <superTypes superTypeName="Physical_entity" supId="70" />
    </superTypes>
  </semType>
  <semType ID="65" name="Animate_being" abbrev="ANIM">
    <definition>WN synset: animal, animate being, beast, brute, creature, fauna</definition>
    <superTypes>
      <superTypes superTypeName="Living_thing" supId="66" />
    </superTypes>
  </semType>
  <semType ID="66" name="Living_thing" abbrev="LIVE">
    <definition>WN synset: organism, being, living thing</definition>
    <superTypes>
      <superTypes superTypeName="Physical_object" supId="68" />
    </superTypes>
  </semType>
  <semType ID="68" name="Physical_object" abbrev="PhysObj">
    <definition>WN synset: object, physical object</definition>
    <superTypes>
      <superTypes superTypeName="Physical_entity" supId="70" />
    </superTypes>
  </semType>
  <semType ID="69" name="Human_act" abbrev="HACT">
    <definition>WN synset (top): act, human action, human activity</definition>
    <superTypes>
      <superTypes superTypeName="Intentional_act" supId="181" />
    </superTypes>
  </semType>
  <semType ID="70" name="Physical_entity" abbrev="PhysEnt">
    <definition>WN synset (top): entity</definition>
    <superTypes>
      <superTypes superTypeName="Ontological_type" supId="178" />
    </superTypes>
  </semType>
  <semType ID="75" name="Event" abbrev="EVNT">
    <definition>WN synset (top): event</definition>
    <superTypes>
      <superTypes superTypeName="State_of_affairs" supId="177" />
    </superTypes>
  </semType>
  <semType ID="76" name="Group" abbrev="GRUP">
